language: C

before_install:
    - cat ./before_install.sh | sh

script:
    - cat ./script.sh | sh

after_script:
    - cat ./after_script.sh | sh

env:
    global:
        secure: bQrYLSk6TpQ6fDohRNSRcWIj4VyjqPj41+kd2yf7VE4OMsVYLVuh2vPQDjfbk1s6PgZZ3uybMk3HQgpwI42NbuxDhpJotRwZDHNoNex9T6hHiAonpOu7WqjKz2cAUqj1Nk2YpcLwATHgb4R9+IjK2OG0nfR80MiLnrzBKrZicgP2k1r8azxKCpg7zz+lUwAnSBTyjK0XMhHJ2JCGFPy3To+04Lno2ifM8VioEdY6vjNFkuopGq5q3bQnK+fnSgc0xyfuBPX+eUiNxj0xJf5GMUNayWbeVT67lecGB9Q4sCbmG90SNkOhhmMUK6PMfVRM+/y6o/VFG7acDa/uP4CxPE/kzJDEE3QMu7otTC3PFAz+7QN2P89XMAARxlrRuN1nrKKsr1pn1+EelBT+bNO9GHevUMjI36pGocFf+g5kG7hfXAOWdHKqfILUCiPz43fUfhbgnp6ztRNUA7sLAnFvii06SvuzChM7NK7aZKrsx0Cu6ELgxut0HnonglMr5m82zqX0zXDCg3VinBTKumDvVrhQOcpdnyHX+9bNfk0yNQvkbSuKYStQCnolntwwd+hopt+IebDFZ7qswv8BvU4a3CmjiRkW7XKcQzGAL0SRSF2pypz6ZOQfHey5UMg7H3gS55Qg9as9u92p33/TA4zahUUqLidVHxv2mwGYzWSjJGI=
