language: C
before_install:
- cat ./before_install.sh | sh
script:
- cat ./script.sh | sh
after_script:
- cat ./after_script.sh | sh
env:
  global:
  - secure: h62N65terF22TYDmUoiu5j1wintKBfdV/31j/CUoxN46TgMkfxDQoe8IvdTB5Dnl8gOR0xOq5V9ShMmsKw2CDQ8bb0b+9ZXR5+cYcin64ik+D1FpIYLQSnVvv+BE1OJh2rcpidg8OVEJVGOkEyytzfsqObq9UtSp4FY/iu8am1JBQC+EtqDAEauKmQ32H3lm6k5/dxNQmmcbBhEhRYV6zaWOokYCn2gM+lkO7TrbjV5koK9Ox5zs/VfIlIdvdWbF5/Y16JD5Vz8eKNJiIJUWO7S5SI0rK8muwsdlBebGlUCJbLgFZRW19aRp6p6KEPqQa3cXA99F4NoSM74a7yS2v3CilD2LWI/bmIcDv5i/6Db5WBbSsv1ZzbJWcqnkNKw9WoxWhXykTiqCfrKwhByNMcjGtMWdgbfHH1RbkdD/+h8SuZkgsWuQIGPWAY3hKQx4kDbv9ZmIu+z4Y4Qno5ugo1OtwwSLcK0k3EwNK1i+joSED/HxfI09g/57DA4YbIE2xi6y5MOnvtPsnyA+UMYUAuqP/gt50GtienPysn4ifijOC9H871J/vkJWOKWmlqb+DQ04oW+hkbfIiPqpD5iwsjbCX6YF4wQ0tFZS5w1S2o7nDMaqRHPkTTsG24t7yxjx+k/a65A3wI8ZokHVTQlZox8zTRBaJ7023aDFGMeF+YU=
