language: c
sudo: false

cache:
  directories: cache

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

before_install:
  - wget https://raw.githubusercontent.com/mpeterv/hererocks/0.3.1/hererocks.py
  - python hererocks.py here --$LUA -r^ --downloads cache --builds cache --no-git-cache
  - export PATH=$PATH:$PWD/here/bin
  - luarocks install lanes
  - luarocks install busted
  - luarocks install luacov

install: luarocks make

script:
  - busted -c
  - luacheck luacheck-scm-1.rockspec -j2
  - luarocks remove luafilesystem --force
  - luarocks remove lanes --force
  - lua -e 'package.path="./src/?.lua;./src/?/init.lua;"..package.path' -lluacov bin/luacheck.lua spec | grep 'I/O error'
  - lua -e 'package.path="./src/?.lua;./src/?/init.lua;"..package.path' -lluacov bin/luacheck.lua --version | grep 'Not found'
  - luarocks remove luacheck --force
  - lua install.lua path/to/luacheck
  - mv src src2
  - path/to/luacheck/bin/luacheck spec/*.lua
  - mv src2 src

after_success:
  - luarocks install luacov-coveralls
  - luacov-coveralls -v
