language: C

before_install:
    - cat ./before_install.sh | sh

script:
    - cat ./script.sh | sh

after_script:
    - cat ./after_script.sh | sh

env:
    global:
        secure: q3aWXO05+1P+sp9oaC+2RN6KSn5Qm+uFjei2eDnNhFj9HyVhQ+shkpOpiOKetWewJtAAUGIJ9LJV8L5G71j8MT1gkaEYrCjYTgI9jbKu96muLdw3nyNw98OuldbHw48M0lMBGM0ekft98vX5bPNk9YjJh+vEoTvk6YWIKElScOKNKHy9cuixs13NQuby6o8sqMZQeVRNGEOcvcL+Z6C+d+JTzck0X/wzTAvaWqU6uD1uJfKgMupG406EDm412nM3QREmhiX30+/PhJpiJz9eA6VHda4jcxBUSRlWOAbLU85EMuv5b4bUcScaXNRBpIMv14n8Z7Ao2KI1XC3Drpz1twWaXOT/h6q29O3Vcr0xZDzzW0SgN04j3wvi+hqOir/dMRP08334uN0ufnFzKWQ31xsNXQgLgSK6xR8yzeSpsBwND3GkvLi4ZYbGn4XtGx8XiG8uerIz66mAlay4CdwACKgw0akLcF2HLl0FOuLpZ+mz2TKpE3SvqagcmuNvSI8vMEaFD+LSdFdQk1oZuQlJBJR1IUmr8JswxS7OqVTGTJomMtbn03ZDk9J38774vU8li0bnW1vbXVSJKfCLJnEEO0hpyfX4W46Wemnbmgz87viGkq9geBBBcf/4buBE+NSRnYse4wewN60uIu89gcv6/3JF/1GVlnBVGGMOkdt4vQE=
