language: C
before_install:
- cat ./before_install.sh | sh
script:
- cat ./script.sh | sh
after_script:
- cat ./after_script.sh | sh
env:
  global:
    secure: PV2KCBhgD7TaXD7IWMzWw49HYjbGKthJVYHaX5/PJNdznosjXIrd56fSSCWgIECJegVYxcZA9jU89qlSSfOLlDP2M6sZkS8gehKN5p8cT9EOnO5QvY3ksRPJnZ4XtfQXduUUNUyrV0bf1ZsbHpDlCbNC+lsf9fJTLd2OJ/GBa3fFgKL8TlZUS0yzClVGDIupzVrILgcAPnWGN8seoZ3m97tvja7i3oSTIAnqyorM9+vNLD1TQIql2MDmlyReqN+JFrPVjTIaIB9NVTW0QBJggrqp3MlJjOZBaffZ2zcjkw1B1KzkMTBtwIW28JwR8HYz6JRfVkl4IzCJJcTZ+40dSD0tV6qnnR34dPV4pxUxE4/Pxn1tnhu73zBQwGRTZ2x4faqDaqlNcruZaalYXoVgrj0ZFdOmeEQx2v7/mMG/+UTDklqmlY3QFhQr/pRo0jESM+sv/Cu3LLv1yEXCd31QuP1rqb/RSuyVM7IsroHNPhz0iaZhzKvUF0R3G9IMbhG5zPTTwmtIjuE6PyeFBQDv3cvwaXisiON1xI/ETLZm527W/RypWIitpuXl1tDsOEpSvSDKmBSYTgBh2r+ift9Z837Lqo97sKad+IUYkLlULmmvcv+snGVCee4l0sP+KXSrZwx0Lt49OvFDNza1xZf+IvXfMC8WjY5kFthpBC7ohv0=
