language: c

env:
  - LUA="Lua 5.1"
  - LUA="Lua 5.2"
  - LUA="Lua 5.3"
  - LUA="LuaJIT 2.0"

before_install:
  - bash .travis_setup.sh
  - bash .travis_setup_rocks.sh

install:
  - sudo luarocks make

script:
  - busted spec
  - luacheck luacheck-scm-1.rockspec -j2
  - sudo luarocks remove luafilesystem --force
  - sudo luarocks remove lanes --force
  - sudo luarocks remove luacheck --force
  - lua install.lua path/to/luacheck
  - rm -r bin src
  - path/to/luacheck/bin/luacheck spec/*.lua
  - path/to/luacheck/bin/luacheck src | grep 'I/O error'
  - path/to/luacheck/bin/luacheck --version | grep 'Not found'
