language: C
before_install:
- cat ./before_install.sh | sh
script:
- cat ./script.sh | sh
after_script:
- cat ./after_script.sh | sh
env:
  global:
    secure: rdXpZ2/875yr3ApbeaZIX7L98QMS4DI87DkKAT4ipqL9DCrjTI3CQhYlT5gAHkiIg0VPpZYp4117HFCYBe9LoKL/wHgvBcDyNdHqrKQJ9X8C5JBOPMx4/YB/FhcDee8Wa+hLFBXhcpm4S47O8fE+N9BxSoNeIzFGkCOyP3Yj2pA+xpdihhXlvbcca7PWHOd36WP0JRYyVGvawlQKiV1WlGsykkvK/STi2zJE2yq1kmbhaY6k7fB5zXHjFEtGDJdRmw2kib13oUlpfGuUvaM4R3J3YfFBR9FrBnvdN/ob1lbPCCxI5vdxTdt0tH5U+NpRNoEd6T0ygeQMzLUFQuoW52NKQWrTertKLrYwhEjfnrMReDojSDeSnCP3w6oj/fptGBpoFuFgbcqALVsGzUUP7ZC6snnolqhsBI2tjyiTtQBbut2CcWeOsDz0ebAL4mXR2cWLxUiHsVoC1baUQw33iNO3sk1AlGiUmngl+h7hTyKGKAIxermIeuTFpYd3f9oFuueEwjY5sCkRC7fjbjs7QVP7bKomEGkgxGV77yb0DKzCLCErnNobkEEqz4OAsO0IRKKmTbPe5zPoHSJ/csywgdCtd8CtlKFYizl1kqG9cgQwJF+DLFyT8hinBU4Q/tDbk0VRdik340rT3ViVXk0s7ryE5fayVen1sYS4rIjBfAg=
