version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.1"

before_build:
  - ps: Invoke-WebRequest https://raw.githubusercontent.com/mpeterv/hererocks/master/hererocks.py -OutFile hererocks.py

build_script:
  - python hererocks.py here --%LUA% -r latest
  - PATH %CD%\here\bin;%PATH%
  - luarocks make
  - luarocks install busted

test_script: busted
